#define KEY_UNDO 0xFF // Special case
#define KEY_HELP KEY_F11 // 0x4075
#define KEYPAD_LPAREN KEY_F12 // KEY_MEDIA_VOLUME_DEC// 0x40B6
#define KEYPAD_RPAREN KEY_F13 // KEY_MEDIA_VOLUME_INC// 0x40B7


uint16_t keymap[] = {
  0,
  KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE,
  KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFT_BRACE, KEY_RIGHT_BRACE, KEY_ENTER,
  MODIFIERKEY_LEFT_CTRL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_QUOTE, KEY_TILDE,
  MODIFIERKEY_LEFT_SHIFT, KEY_BACKSLASH, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH, MODIFIERKEY_RIGHT_SHIFT, KEY_CAPS_LOCK,
  MODIFIERKEY_LEFT_GUI, KEY_SPACE, MODIFIERKEY_RIGHT_ALT,
  KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12,
  KEY_HOME,   KEY_UP,   0,         KEYPAD_MINUS,
  KEY_LEFT,   0,        KEY_RIGHT, KEYPAD_PLUS,
  0,          KEY_DOWN, 0,         KEY_INSERT,
  KEY_DELETE, 0,        0,         KEY_NON_US_NUM, /*ISO KEY*/
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  KEY_UNDO,   KEY_HELP,
  KEYPAD_LPAREN, KEYPAD_RPAREN, KEYPAD_SLASH, KEYPAD_ASTERIX,
  KEYPAD_7, KEYPAD_8, KEYPAD_9, 
  KEYPAD_4, KEYPAD_5, KEYPAD_6,
  KEYPAD_1, KEYPAD_2, KEYPAD_3,
  KEYPAD_0, KEYPAD_PERIOD, KEYPAD_ENTER,
};

